api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import ItemViewSet, OrderViewSet

app_name = 'api'

router_v1 = routers.DefaultRouter()

router_v1.register('items', ItemViewSet, basename='items')
router_v1.register(r'orders', OrderViewSet, basename='orders')

urlpatterns = [
    path('api/', include(router_v1.urls)),
]

store/urls.py
from django.urls import path
from store.views import (ItemDetailView,
                         category_products,
                         CheckoutView,
                         HomeView,
                         OrderSummaryView,
                         add_to_cart,
                         products,
                         remove_from_cart,
                         remove_single_item_from_cart,
                         AddCouponView,
                         RequestRefundView)

app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', products, name='products'),
    path('category/<int:category_id>/', category_products, name='category_products'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/',
         remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

tstore/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('store.urls', namespace='store')),
    path('', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

store/models.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField

from store.validators import validate_min_value

User = get_user_model()


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True,
        verbose_name=_('Title')
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        verbose_name=_('SLUG')
    )

    class Meta:
        ordering = ('name',)
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Tag(models.Model):
    title = models.CharField(
        max_length=50,
        unique=True,
        verbose_name=_('Title')
    )
    color = models.CharField(
        max_length=7,
        verbose_name=_('Color'),
        help_text=_('Hex color code, e.g., #ABC123 or #DDD')
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        verbose_name=_('SLUG')
    )

    class Meta:
        ordering = ('title',)
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name=_('Title')
    )
    discount_price = models.FloatField(
        verbose_name=_('Discount price'),
        validators=[validate_min_value],
        null=True,
        blank=True,
    )
    price = models.FloatField(
        verbose_name=_('Price'),
        validators=[validate_min_value]
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name=_('Category')
    )
    label = models.ManyToManyField(
        Tag,
        verbose_name=_('Tags')
    )
    slug = models.SlugField(
        unique=True,
        max_length=255,
        verbose_name=_('SLUG')
    )
    description = models.TextField(
        verbose_name=_('Description')
    )
    image = models.ImageField(
        upload_to='images/items/',
        verbose_name=_('Image')
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created date')
    )

    def get_absolute_url(self):
        return reverse("store:product",
                       kwargs={'slug': self.slug}
                       )

    def get_add_to_cart_url(self):
        return reverse(
            "store:add-to-cart",
            kwargs={'slug': self.slug}
        )

    def get_remove_from_cart_url(self):
        return reverse(
            "store:remove-from-cart",
            kwargs={'slug': self.slug}
        )

    class Meta:
        ordering = ('-created_at',)
        verbose_name = _('Item')
        verbose_name_plural = _('Items')

    def __str__(self):
        return self.title


class Address(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('User')
    )
    street_address = models.CharField(
        max_length=100,
        verbose_name=_('Street address')
    )
    country = CountryField(
        multiple=False,
        verbose_name=_('Country')
    )
    zip = models.CharField(
        max_length=100,
        verbose_name=_('Zip code')
    )

    default = models.BooleanField(
        default=False,
        verbose_name=_('Default')
    )

    class Meta:
        ordering = ('country',)
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

    def __str__(self):
        return self.user.username


class OrderStatus(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name=_('Status Name')
    )
    description = models.TextField(
        blank=True,
        verbose_name=_('Status Description')
    )

    class Meta:
        ordering = ('name',)
        verbose_name = _('Order Status')
        verbose_name_plural = _('Order Statuses')

    def __str__(self):
        return self.name


class OrderItem(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('User')
    )
    ordered = models.BooleanField(
        default=True,
        verbose_name=_('Ordered')
    )
    item = models.ForeignKey(
        Item,
        related_name='items',
        on_delete=models.CASCADE,
        verbose_name=_('Product')
    )
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name=_('Quantity')
    )

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return (self.get_total_item_price()
                - self.get_total_discount_item_price())

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    class Meta:
        ordering = ('item',)
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')

    def __str__(self):
        return f"{self.quantity} - {self.item.title}"


class Order(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('User')
    )
    ref_code = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name=_('Refund code')
    )
    items = models.ManyToManyField(
        OrderItem,
        verbose_name=_('Products')
    )
    start_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Start date')
    )
    ordered_date = models.DateTimeField(
        verbose_name=_('Ordered date')
    )
    ordered = models.BooleanField(
        default=False,
        verbose_name=_('Ordered')
    )
    shipping_address = models.ForeignKey(
        'Address',
        related_name='shipping_address',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('Shipping Address')
    )

    # payment = models.ForeignKey(
    #     'Payment',
    #     on_delete=models.SET_NULL,
    #     blank=True,
    #     null=True,
    #     verbose_name=_('Payment')
    # )
    coupon = models.ForeignKey(
        'Coupon',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('Coupon')
    )
    status = models.ForeignKey(
        OrderStatus,
        on_delete=models.SET_NULL,
        related_name='status',
        blank=True,
        null=True,
        verbose_name=_('Order Status')
    )

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    class Meta:
        ordering = ('-ordered_date',)
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('User')
    )
    amount = models.FloatField(
        verbose_name=_('Amount'),
        validators=[validate_min_value]
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Timestamp')
    )

    class Meta:
        ordering = ('-timestamp',)
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(
        max_length=15,
        verbose_name=_('Promo Code')
    )
    amount = models.FloatField(
        verbose_name=_('Discount amount'),
        validators=[validate_min_value]
    )

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name=_('Order')
    )
    reason = models.TextField(
        verbose_name=_('Reason')
    )
    accepted = models.BooleanField(
        default=False,
        verbose_name=_('Accepted')
    )
    email = models.EmailField(
        verbose_name=_('E-mail')
    )

    def __str__(self):
        return f"{self.pk}"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/category_products.html
{% extends "base.html" %}

{% block content %}
<main>
  <div class="container">
    <h1>Категория <b>{{ category.name }}</b></h1>
    <div class="row">
      {% for item in items %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{{ item.image.url }}" alt="{{ item.title }}" class="bd-placeholder-img card-img-top" width="320"
               height="320">
          <div class="card-body">
            <h5 class="card-title">{{ item.title }}</h5>
            <p class="card-text">Цена: {{ item.price }}₽</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{{ item.get_absolute_url }}" class="btn btn-sm btn-outline-secondary">Подробнее</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">
  <hr class="my-4">

  <div class="footer-content">
    <div class="mr-auto">
      <a href="{% url 'store:request-refund' %}" target="_blank">
        <i class="fab fa-revert mr-3"></i>Запросить возврат
      </a>
    </div>

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://t.me/Sergey8951" target="_blank">
        <i class="fab fa-telegram mr-5"></i>
      </a>
    </div>
    <!-- Social icons -->
  </div>

  <!--Copyright-->
  <div class="footer-copyright py-2">
    <a href="#" target="_blank"> © TStore 2023</a>
  </div>
  <!--/.Copyright-->

  <style>
    .footer-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
  </style>
</footer>

templates/home.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
      <!-- Navbar brand -->
      <span class="navbar-brand">Категории:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
              aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:home' %}">Все
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:category_products' category.id %}">{{ category.name }}</a>
          </li>
          {% endfor %}
        </ul>
        <!-- Links -->

        <form class="form-inline" method="get" action="{% url 'store:products' %}" id="search-form">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" name="q" id="search-input" placeholder="Поиск"
                   aria-label="Search">
            <button class="btn btn-primary" type="submit">Поиск</button>
          </div>
        </form>

      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <div class="row wow fadeIn">
        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <div class="view overlay">
              <img src="{{ item.image.url }}" alt="{{ item.title }}" class="card-img-top" width="320" height="320">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <div class="card-body text-center">
              <a href="{% url 'store:category_products' item.category.id %}" class="grey-text">
                <h5>{{ item.category.name }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                  {% for tag in item.label.all %}
                  <span class="badge badge-pill" style="background-color: {{ tag.color }}">{{ tag.title }}</span>
                  {% endfor %}
                </strong>
              </h5>
              <h4 class="font-weight-bold blue-text">
                <strong>
                  {% if item.discount_price %}
                  <span class="text-danger">{{ item.discount_price }}₽</span>
                  <del>{{ item.price }}₽</del>
                  {% else %}
                  {{ item.price }}₽
                  {% endif %}
                </strong>
              </h4>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
    <!--Section: Products v.3-->


    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Предыдущая</span>
          </a>
        </li>
        {% endif %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Следующая</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
  </div>
</main>
{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg mdb-color lighten-3 scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <strong class="white-text">TStore</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'store:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Корзина </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link waves-effect">
            <i class="fas fa-user"></i>
            <span class="clearfix d-none d-sm-inline-block"> {{ request.user.username }}</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Выход </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Вход </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Регистрация </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Ваша корзина</span>
    <span class="badge badge-success badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">{{ order_item.get_final_price }}₽</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div>
        <h6 class="my-0">Промокод</h6>
        <p class="text-muted">{{ order.coupon.code }}</p>
        </div>
        <span class="text-danger">-{{ order.coupon.amount }}₽</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Итог (RUB)</span>
        <strong>{{ order.get_total }}₽</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'store:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-success btn-md waves-effect m-0" type="submit">Применить</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
  <div class="container">

    <div class="table-responsive text-nowrap">
      <h2>Информация о заказе</h2>
      <table class="table">
        <thead>
        <tr>
          <th scope="col">№</th>
          <th scope="col">Название</th>
          <th scope="col">Цена</th>
          <th scope="col">Количество</th>
          <th scope="col">Цена со скидкой</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ order_item.item.title }}</td>
          <td>{{ order_item.item.price }}₽</td>
          <td>
            <a href="{% url 'store:remove-single-item-from-cart' order_item.item.slug %}"><i
                    class="fas fa-minus mr-2"></i></a>
            {{ order_item.quantity }}
            <a href="{% url 'store:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
          </td>
          <td>
            {% if order_item.item.discount_price %}
            {{ order_item.get_total_discount_item_price }}₽
            <span class="badge badge-primary">Выгода {{ order_item.get_amount_saved }}₽</span>
            {% else %}
            {{ order_item.get_total_item_price }}₽
            {% endif %}
            <a style='color: red;' href="{% url 'store:remove-from-cart' order_item.item.slug %}">
              <i class="fas fa-trash float-right"></i>
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan='5'>Ваша корзина пуста</td>
        </tr>
        <tr>
          <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Продолжить покупки</a>
          </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="4"><b>Промокод</b></td>
          <td><b class="text-danger">-{{ object.coupon.amount }}₽</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
          <td colspan="4"><b>Общая сумма заказа</b></td>
          <td><b>{{ object.get_total }}₽</b></td>
        </tr>
        <tr>
          <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Оформить заказ</a>
            <a class='btn btn-primary float-right' href='/'>Продолжить покупки</a>
          </td>
        </tr>
        {% endif %}
        </tbody>
      </table>

    </div>

  </div>
</main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}
{% block content %}
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <h1 class="dark-grey-text mb-4">{{ item.title }}</h1>
        <img width="520" height="520" src="{{ object.image.url }}" class="img-fluid" alt="{{ object.title }}">
      </div>
      <!--Grid column-->
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <!--Content-->
        <div class="p-4">
          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{ object.get_category_display }}</span>
            </a>
          </div>
          <p class="lead">
            {% if object.discount_price %}
            <span class="mr-1">
                <del>{{ object.price }}₽</del>
              </span>
            <span>{{ object.discount_price }}₽</span>
            {% else %}
            <span>{{ object.price }}₽</span>
            {% endif %}
          </p>
          <p class="lead font-weight-bold">Описание</p>
          <p>{{ object.description }}</p>
          {% comment %}
          <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">
              Добавить в корзину
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>
          </form>
          {% endcomment %}
          <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
            Добавить в корзину
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
          <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
            Удалить из корзины
          </a>
        </div>
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
    <hr>
    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">Вам также может понравиться</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">
        <img src="https://media2.giphy.com/media/l1BgQyDWiGOJ7kuo8/giphy.gif?cid=ecf05e47e45ug7ps02afoejurzybdbz2nf6c55yxrol13wqp&ep=v1_gifs_search&rid=giphy.gif&ct=g"
             class="img-fluid" alt="boost1">
      </div>
      <!--Grid column-->
      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img src="https://media4.giphy.com/media/VCMmZdprB9GJa/giphy.gif?cid=ecf05e472nihatjztszorg2sezjipmbok9wq9tr4fxhebyy1&ep=v1_gifs_search&rid=giphy.gif&ct=g"
             class="img-fluid" alt="watch">
      </div>
      <!--Grid column-->
      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img src="https://media1.giphy.com/media/l0HlyfuWXlR0FWLUQ/giphy.gif?cid=ecf05e47p2kc5ave1uc7bjug5rcxd1q0531etjkytpirz0z3&ep=v1_gifs_related&rid=giphy.gif&ct=g"
             class="img-fluid" alt="boost2">
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
</main>
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Запросить возврат</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Отправить</button>
    </form>

    </div>
  </main>

{% endblock content %}